library(dplyr)
library(tm)
set.seed(1310)
blogs <- readLines("./en_US/en_US.blogs.txt")
blogs.samples <- sample(blogs, length(blogs) * 0.2)
news <- readLines("./en_US/en_US.news.txt")
news.samples <- sample(news, length(news) * 0.2)
twitter <- readLines("./en_US/en_US.twitter.txt")
twitter.samples <- sample(twitter, length(twitter) * 0.2)
rm(blogs, news, twitter)